import Head from "next/head";
import MyPieChart from "@/components/charts/piechart";

export default function Home({ data, setData }) {
  function handleSubmit(event) {
    event.preventDefault();
    const newData = [
      {
        name: "Groceries",
        value: parseInt(event.target.elements.groceries.value),
        color: "grey",
      },
      {
        name: "House",
        value: parseInt(event.target.elements.house.value),
        color: "blue",
      },
      {
        name: "Fun",
        value: parseInt(event.target.elements.fun.value),
        color: "red",
      },
      {
        name: "Children",
        color: "green",
        value: parseInt(event.target.elements.children.value),
      },
      {
        name: "Savings",
        color: "violet",
        value: parseInt(event.target.elements.savings.value),
      },
    ];
    setData(newData);
  }

  return (
    <>
      <Head>
        <title>Finanzen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>INSIGHT</h1>
        <form
          onSubmit={(event) => {
            handleSubmit(event);
          }}
        >
          <label htmlFor="house">
            House:
            <input id="house" type="text"></input>
          </label>
          <br />
          <label htmlFor="groceries">
            Groceries:
            <input id="groceries" type="text"></input>
          </label>
          <br />
          <label htmlFor="fun">
            Fun:
            <input id="fun" type="text"></input>
          </label>
          <br />
          <label htmlFor="children">
            Children:
            <input id="children" type="text"></input>
          </label>
          <br />
          <label htmlFor="savings">
            Savings:
            <input id="savings" type="text"></input>
          </label>
          <br />
          <button>Save</button>
        </form>
        <MyPieChart data={data}></MyPieChart>
      </main>
    </>
  );
}
